// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 1
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){







var lb=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var mb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,nb=function(a){if(null==a)return String(a);var b=mb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},ob=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},xa=function(a){if(!a||"object"!=nb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!ob(a,"constructor")&&!ob(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||ob(a,b)},Fa=function(a,b){var c=b||("array"==nb(a)?[]:{}),d;for(d in a)if(ob(a,d)){var e=a[d];"array"==nb(e)?("array"!=nb(c[d])&&(c[d]=[]),c[d]=Fa(e,c[d])):xa(e)?(xa(c[d])||(c[d]={}),c[d]=Fa(e,c[d])):c[d]=e}return c};var Xa=null,pb=Math.random(),qb=null,ma=null,Da=!1,rb={},sb={},Ea={};var Ga,Ha,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,U,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,
ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf;
(function(){var a=function(a){return{toString:function(){return a}}};tb=a("");ub=a("");vb="";wb=a("");xb=a("");yb=a("");zb=a("");Ab=a("");Bb=a("");Cb=a("");Db=a("");Eb=a("0");U=a("1");Fb=a("");Gb=a("");Hb=a("");
Ib=a("");Jb=a("");Kb=a("");Lb=a("");Mb=a("");Nb=a("");Ob=a("");Pb=a("");Qb=a("");Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("");
Wb=a("");Xb=a("");Yb=a("");Zb=a("");$b=a("");ac=a("");bc=a("2");cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");
mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");rc=a("");sc=a("");tc=a("");uc=a("");vc=a("");xc=a("");yc=a("");zc=a("");Ac=a("");Bc=a("");Cc=a("");Dc=a("");
Ec=a("");Fc=a("");Gc=a("");Hc=a("");Ic=a("");Jc=a("");Kc=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");
Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=a("");ad=a("");bd=a("");cd=a("");dd=a("");Ga=a("3");ed=a("");fd=a("8");gd=a("9");hd=a("");id=a("");
jd=a("4");kd=a("");ld=a("");md=a("");nd=a("");od=a("");Ha=a("5");pd=a("");qd=a("");rd=a("");sd=a("");td=a("");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("");zd=a("");Ad=a("");Bd=a("");
Cd=a("");Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("6");Sd=a("");Td=a("");Ud=a("");Vd=a("");
Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("");le=a("");me=a("");ne=a("");
oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("7");De=
a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("");
Ue=a("");Ve=a("");We=a("");Xe=a("");Ye=a("");Ze="";$e=a("");af=a("");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=a("");hf=a("");jf=a("");kf=a("");lf=
a("");mf=a("");nf=a("");of=a("");pf=a("")})();var va=function(a,b){Fa(a,b)},gb=function(){},P=function(a){return"function"==typeof a},Ua=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},qf=function(a){return"number"==nb(a)&&!isNaN(a)},rf=function(a){return/^[0-9]+$/.test(a)},sf=function(a){return"string"==nb(a)},tf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},la=function(a){return a?a.replace(/^\s+|\s+$/g,""):
""},R=function(a){return Math.round(Number(a))||0},Aa=function(a){return"false"==String(a).toLowerCase()?!1:!!a},uf=function(a){var b=[];if(Ua(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},G=function(){return new Date},sa=function(a,b){if(!qf(a)||!qf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},vf=function(){this.prefix="gtm.";this.values={}};vf.prototype.set=function(a,b){this.values[this.prefix+a]=b};
vf.prototype.get=function(a){return this.values[this.prefix+a]};vf.prototype.contains=function(a){return void 0!==this.get(a)};
var wf=function(a,b,c){try{if(!a[Ed])return a[Ga](a,b||gb,c||gb);c&&c()}catch(d){}return!1},yf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=la(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},zf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Af=function(a){return function(){return a("GTM-M63JRHD")}},Bf=function(a){for(var b=0;b<a.length;b++)a[b]()},wa=function(){return"gtm"+Cf()},
Cf=function(){var a=Xa.sequence||0;Xa.sequence=a+1;return a},ya=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Df=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Ef=function(a,b){0==b?a.gb=!0:a.Z=!0;var c=a.g;a.i&&(a.i.Ma[c]=b);rb[c]&&(rb[c].state=b)},Ff=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var x=window,N=document,Hf=navigator,S=function(a,b){var c=x[a];x[a]=void 0===c?b:c;return x[a]},M=function(a,b,c,d){return(d||"http:"!=x.location.protocol?a:b)+c},If=function(a){var b=N.getElementsByTagName("script")[0]||N.body||N.head;b.parentNode.insertBefore(a,b)},ab=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},t=function(a,b,c){var d=N.createElement("script");d.type="text/javascript";d.async=
!0;d.src=a;ab(d,b);c&&(d.onerror=c);If(d);return d},ga=function(a,b){var c=N.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";If(c);ab(c,b);void 0!==a&&(c.src=a);return c},F=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},T=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},v=function(a){x.setTimeout(a,0)},cb=!1,
db=[],Jf=function(a){if(!cb){var b=N.createEventObject,c="complete"==N.readyState,d="interactive"==N.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){cb=!0;for(var e=0;e<db.length;e++)v(db[e])}db.push=function(){for(var a=0;a<arguments.length;a++)v(arguments[a]);return 0}}},Kf=0,Lf=function(){if(!cb&&140>Kf){Kf++;try{N.documentElement.doScroll("left"),Jf()}catch(a){x.setTimeout(Lf,50)}}},ia=function(a){var b=N.getElementById(a);if(b&&ja(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(ja(document.all[a][c],
"id")==a)return document.all[a][c];return b},ja=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Sa=function(a){return a.target||a.srcElement||{}},ka=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},kb=function(a){var b=N.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},
Ta=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},Mf=!1,Nf=[],Of=function(){if(!Mf){Mf=!0;for(var a=0;a<Nf.length;a++)v(Nf[a])}},Pf=function(a){a=a||x;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},hb=function(a){window.console&&window.console.log&&window.console.log(a)};var qa=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||x.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||x.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:x.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=
f.split("/");0<=tf(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var l=f.split("&"),m=0;m<l.length;m++){var n=l[m].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},pa=function(a){var b="";if(a&&a.href)var c=a.href.indexOf("#"),b=0>c?a.href:a.href.substr(0,c);
return b},oa=function(a){var b=N.createElement("a");a&&(b.href=a);return b};var Ba=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ea=function(a,b,c){F(a,b,c)},fa=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=qa(oa(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},O=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},Za=function(a,b){for(var c=
[],d=0;a&&d<a.length;d++)a[d]&&a[d].hasOwnProperty(b)&&c.push(a[d][b]);return c};var Qf=new vf,Rf={},Tf={set:function(a,b){Fa(Sf(a,b),Rf)},get:function(a){return V(a,2)},reset:function(){Qf=new vf;Rf={}}},V=function(a,b){if(2==b){var c=a.split(".");for(var f=Rf,e=0;e<c.length;e++){if(void 0===f[c[e]])return;f=f[c[e]]}return f}return Qf.get(a)},Uf=function(a,b){Qf.set(a,b);Fa(Sf(a,b),Rf)},Sf=function(a,b){for(var c={},d=c,e=a.split("."),
f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Vf=!1,Wf=!1;var Xf=Math.random(),Yf="0.100000">Xf;
var Zf=function(a,b){if(Yf){var c="//www.googletagmanager.com/a?id=GTM-M63JRHD&cv=1",d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",G().getTime()-R(qb));c+="&sr=0.100000";d("&ps=",Xf);d("&cb=",sa());F(c)}},$f=gb,ag=function(){var a=!1;};var cg=function(a){var b=Xa.zones;return b?b.checkState("GTM-M63JRHD",a):bg},bg={active:!0,isWhitelisted:function(){return!0}};var eg=gb,fg=[],gg=!1,ta=function(a){return x["dataLayer"].push(a)},hg=function(a){var b=!1;return function(){!b&&P(a)&&v(Af(a));b=!0}},ig=function(a){},og=function(){for(var a=!1;!gg&&0<fg.length;){gg=!0;var b=fg.shift();if(P(b))try{b.call(Tf)}catch(W){}else if(Ua(b))a:{var c=b;if(sf(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Rf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(W){}}}else{var n=void 0,q=void 0,u=b;for(q in u)u.hasOwnProperty(q)&&Uf(q,u[q]);var y=!1,r=u.event;if(r){u.hasOwnProperty("gtm.uniqueEventId")||(u["gtm.uniqueEventId"]=Cf(),Uf("gtm.uniqueEventId",u["gtm.uniqueEventId"]));
n=u["gtm.uniqueEventId"];ma=r;var z=cg(n);if(z.active){var B=hg(u.eventCallback),A=u.eventTimeout;A&&x.setTimeout(B,Number(A));y=eg(n,r,z.isWhitelisted,B,u.eventReporter)}}qb||(qb=u["gtm.start"])&&$f();var C=u,I=n,K=r,E=Rf;if(!y){var J=n,H=r;}ma=null;a=y||a}var Q=b,L=Rf;ng();gg=!1}return!a},pg=function(){var a=og();try{var b=x["dataLayer"].hide;if(b&&void 0!==b["GTM-M63JRHD"]&&b.end){b["GTM-M63JRHD"]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},qg=function(){var a=S("dataLayer",[]),b=S("google_tag_manager",{}),b=
b["dataLayer"]=b["dataLayer"]||{};db.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Nf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(fg.push.apply(fg,b);300<this.length;)this.shift();return og()};fg.push.apply(fg,a.slice(0));v(pg)};var Ra=function(a,b,c){T(a,b,c,void 0)},da=function(a,b,c){t(a,b,c)},na=function(a,b){return V(a,b||2)},aa=function(a,b){x[a]=b},p=function(a,b,c){var d=x;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},w=function(a,b,c,d){return(d||"http:"!=x.location.protocol?a:b)+c};var rg=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),sg={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},tg={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},ug=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},vg=function(a){var b=V("gtm.whitelist");
var c=b&&ug(uf(b),sg),d=V("gtm.blacklist")||V("tagTypeBlacklist")||[];rg.test(x.location&&x.location.hostname)&&(d=uf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&ug(uf(d),tg),f={};return function(g){var h=g&&g[Ga];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>tf(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>
tf(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var q;if(!(q=0<=tf(e,h.a)))a:{for(var u=h.b||[],y=new vf,r=0;r<e.length;r++)y.set(e[r],!0);for(r=0;r<u.length;r++)if(y.get(u[r])){q=!0;break a}q=!1}n=q}return f[h.a]=!k||n}};var ha=function(a){var b=N;return wg?b.querySelectorAll(a):null},xg=!1;if(N.querySelectorAll)try{var yg=N.querySelectorAll(":root");yg&&1==yg.length&&yg[0]==N.documentElement&&(xg=!0)}catch(a){}var wg=xg;var _eu=function(a){var b=String(V("gtm.elementUrl")||a[Cc]||""),c=oa(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return ma};_e.a="e";_e.b=["google"];var Dg=/(^|\.)doubleclick\.net$/i,Eg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Va=function(a){for(var b=String(N.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=la(e[0]);if(f&&f==a){var g=la(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},Fg=function(a,b,c,d,e){if(Dg.test(N.location.hostname)||"/"==c&&Eg.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=N.cookie;N.cookie=f;return g!=
N.cookie||0<=tf(Va(a),b)},Gg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},Hg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},Ig=function(){var a=qa(x.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var Jg=function(a,b){this.h=a;this.o=b};Jg.prototype.toString=function(){var a=""+this.h;1<this.o&&(a=a+"-"+this.o);return a};var Kg=function(a,b){this.Ka=a;this.pa=b};Kg.prototype.toString=function(){return""+this.pa+"."+this.Ka};var Ng=function(a,b){var c=new Lg(null,a,b);Mg(c);return c},Lg=function(a,b,c){this.Wa=Math.floor(G().getTime()/864E5);this.oa=b||"auto";this.fa=c||"/";var d=Gg(this.oa),e=Hg(this.fa);this.H=a||new Jg(d,e);this.j=[];this.D=new vf},Pg=function(a,b,c){b&&(""==c.Ka?Og(a,b):(a.D.contains(b)||a.j.push(b),a.D.set(b,c)))},Qg=function(a,b){for(var c=0;c<b.length;c++)Pg(a,b[c][0],b[c][1])},Og=function(a,b){var c=tf(a.j,b);0<=c&&a.j.splice(c,1);a.D.set(b,void 0)},Rg=function(a){for(var b=[],c=0;c<a.j.length;c++){var d=
a.j[c];b.push([d,a.D.get(d)])}return b},Sg=function(a){for(var b=0,c=0;c<a.j.length;c++)b=Math.max(b,a.D.get(a.j[c]).pa);return 864E5*b};Lg.prototype.toString=function(){if(0==this.j.length)return"";for(var a=[],b=0;b<this.j.length;b++){var c=this.j[b];a.push(""+c+"."+this.D.get(c).toString())}return"GAX1."+this.H.toString()+"."+a.join("!")};
var Tg=function(a,b){for(var c=new Date,d=Hg(a.fa),e=[],f=0;f<a.j.length;f++){var g=a.j[f];a.D.get(g).pa<a.Wa&&e.push(g)}for(f=0;f<e.length;f++)Og(a,e[f]);if(a.j.length>(b||10))return!1;c.setTime(Sg(a));if("auto"!=a.oa)return Fg("_gaexp",a.toString(),a.fa,a.oa,c);for(var h=Ig(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.H=new Jg(Gg(h[k]),d),Fg("_gaexp",a.toString(),a.fa,h[k],c)))return!0;return!1},Mg=function(a){for(var b=a.H.h,c=a.H.o,d=Va("_gaexp"),e=[],f=0;f<d.length;f++){var g=Ug(a,d[f]);g&&e.push(g)}Ff(e,
function(a,d){var e=a.H,f=d.H;return e.h==f.h&&e.o==f.o?!1:e.h==b&&e.o==c?!0:f.h==b&&f.o==c?!1:e.h==b?f.h!=b||e.o<f.o:f.h==b?!1:e.o==c?f.h!=b&&(f.o!=c||e.h<f.h):f.o==c?!1:e.h<f.h||e.h==f.h&&e.o<f.o});a.H=0<e.length?e[0].H:new Jg(b,c);for(f=e.length-1;0<=f;f--)Qg(a,Rg(e[f]))},Ug=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=la(e[0]);if(0!=f.length){var g=2==e.length?la(e[1]):"1";if(rf(f)&&rf(g)){d=new Jg(R(f),R(g));
break a}}}d=void 0}if(d){for(var h=new Lg(d,a.oa,a.fa),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!rf(m[1]))return;Pg(h,m[0],new Kg(m[2],R(m[1])))}}return h}}};var _f=function(a){var b=String(V("gtm.referrer")||N.referrer);if(!b)return b;var c=oa(b);return b};_f.a="f";_f.b=["google"];var Yg=function(a){var b=x.location,c;(c=a[qc]?a[qc]:V("gtm.url"))&&(b=oa(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[bc]&&(f=qa(b,a[bc],a[we],a[Bc],a[je]));return f},_u=Yg;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[Eb])==String(a[U])};_eq.a="eq";_eq.b=["google"];var Wa=new String("undefined"),eb=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Wa?b:a[d]);return c.join("")}};eb.prototype.toString=function(){return this.resolve("undefined")};eb.prototype.valueOf=eb.prototype.toString;var hh={},fb=function(a,b){var c=Cf();hh[c]=[a,b];return c},ih=function(a){var b=a?0:1;return function(a){var c=hh[a];if(c&&P(c[b]))c[b]();hh[a]=void 0}};var jh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},kh=function(a,b){return a<b?-1:a>b?1:0};var lh;a:{var mh=lb.navigator;if(mh){var nh=mh.userAgent;if(nh){lh=nh;break a}}lh=""}var X=function(a){return-1!=lh.indexOf(a)};var oh=function(){X("iPod")},ph=function(){return X("iPhone")&&!X("iPod")&&!X("iPad")};var qh=function(a){qh[" "](a);return a};qh[" "]=function(){};var sh=function(a,b){var c=rh;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var th=X("Opera"),uh=X("Trident")||X("MSIE"),vh=X("Edge"),wh;if(wh=X("Gecko")){var xh=lh.toLowerCase();wh=!(-1!=xh.indexOf("webkit")&&!X("Edge"))}var yh=wh&&!(X("Trident")||X("MSIE"))&&!X("Edge"),zh=lh.toLowerCase(),Ah=-1!=zh.indexOf("webkit")&&!X("Edge");Ah&&X("Mobile");X("Macintosh");X("Windows");X("Linux")||X("CrOS");var Bh=lb.navigator||null;Bh&&(Bh.appVersion||"").indexOf("X11");X("Android");ph();X("iPad");oh();ph()||X("iPad")||oh();
var Ch=function(){var a=lb.document;return a?a.documentMode:void 0},Dh;a:{var Eh="",Fh=function(){var a=lh;if(yh)return/rv\:([^\);]+)(\)|;)/.exec(a);if(vh)return/Edge\/([\d\.]+)/.exec(a);if(uh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ah)return/WebKit\/(\S+)/.exec(a);if(th)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Fh&&(Eh=Fh?Fh[1]:"");if(uh){var Gh=Ch();if(null!=Gh&&Gh>parseFloat(Eh)){Dh=String(Gh);break a}}Dh=Eh}
var Hh=Dh,rh={},Ih=function(a){return sh(a,function(){for(var b=0,c=jh(String(Hh)).split("."),d=jh(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=kh(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||kh(0==k[2].length,0==l[2].length)||kh(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})},Jh;
var Kh=lb.document;Jh=Kh&&uh?Ch()||("CSS1Compat"==Kh.compatMode?parseInt(Hh,10):5):void 0;var Lh;if(!(Lh=!yh&&!uh)){var Mh;if(Mh=uh)Mh=9<=Number(Jh);Lh=Mh}Lh||yh&&Ih("1.9.1");uh&&Ih("9");var jb=function(a,b){var c="";uh&&!Nh(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Oh)a.srcdoc=d;else if(Ph){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Qh(a,d)},Oh=Ah&&"srcdoc"in document.createElement("iframe"),Ph=yh||Ah||uh&&Ih(11),Qh=function(a,b){uh&&Ih(7)&&!Ih(10)&&6>Rh()&&Sh(b)&&(b=Th(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};uh&&!Nh(a)?Uh(a,c):c()},Rh=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Nh=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{qh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},Vh=0,Uh=function(a,b){var c="goog_rendering_callback"+Vh++;lb[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Sh=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Th=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var Xh=function(a,b,c,d){return function(){try{if(0<b.length){var e=b.shift(),f=Xh(a,b,c,d);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=N.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,ab(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);Xh(e,k,f,d)()}else a.insertBefore(e,null),f()}else c()}catch(l){v(d)}}};var Zh=function(a,b,c){if(N.body){var d=
a[jd];d instanceof eb&&(d=d.resolve(fb(b,c)),b=gb);if(a[ff])try{jb(ga(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+d),v(b)}catch(e){v(c)}else a[hf]?Yh(d,b,c):Xh(N.body,kb(d),b,c)()}else x.setTimeout(function(){Zh(a,b,c)},200)},_html=Zh;_html.a="html";_html.b=["customScripts"];
var ki=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=hi(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=ii(f,g);ji(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},li=null,hi=function(a){if(li)return li;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return li=
c}0==a.styleSheets.length&&a.createStyleSheet();return li=a.styleSheets[0]},ii=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},ji=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var si={},ti=void 0,ui=function(a){var b=si[a];b||(b={id:a,w:[],ca:0,Oa:null,Da:void 0,Ha:!1},si[a]=b);ti=b},wi=function(a,b,c,d){var e=ti;if(!wg||!e)return!1;var f={id:e.id+":"+e.w.length,ob:b,Y:[],jb:c,I:a,za:0,xa:d||null,Va:0,ba:!1};e.w.push(f);null===a?(f.ba=!0,b(null)):vi(e);return!0},xi=function(a){var b=ki(a,"visibility","hidden",!0);return function(){P(b)&&b.apply();b=null}},yi=function(a,b,c,d){var e=b;if(!cb){var f=xi(a.B);db.push(f);e=function(a,c){var d=b(a,c);f();return d}}return wi(a,
e,c,d)},vi=function(a){if(!a.Ha){for(var b=a.ca;b<a.w.length;b++){var c=a.w[b],d=b==a.ca;if(!c.ba&&!zi(d,c))break;c.ba&&d&&a.ca++}a.w.length>a.ca?(a.Oa||(a.Oa=x.setTimeout(function(){a.Oa=null;vi(a)},80)),cb||a.Da||(a.Da=function(){v(function(){vi(a)})},T(N,"DOMContentLoaded",a.Da))):Ai(a)}},Ai=function(a){for(var b=0;b<a.w.length;b++){var c=a.w[b];if(c.I)for(var d=ha(c.I.B)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Bi(f,c.id),c.Y.push(Ci(f,c.id)))}}},
zi=function(a,b){var c=[];if(b.I){var d=Di(b.I,b.id),e=null;b.xa&&(e=Di(b.xa,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!cb&&(null===b.xa.u||b.Va+c.length<b.xa.u)))break;c.push({element:g,$b:h})}}if(!cb&&b.jb&&(!a||null==b.I.u||b.I.u!=b.za+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].$b,n;b.za++;Bi(l,b.id);m&&(b.Va++,n=b.id+"-t",Bi(m,n));var q=b.ob(l,m);P(q)&&b.Y.push(q);b.Y.push(Ci(l,b.id));m&&n&&b.Y.push(Ci(m,n))}if(b.I.u&&
b.I.u==b.za||cb)b.ba=!0;return!0},Bi=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Ci=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Di=function(a,b){for(var c=ha(a.B)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.G&&!Ei(f))break;d.push(f)}}return d},Ei=function(a){if(cb)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Ja,Fi,Gi,Pa=/(Firefox\D28\D)/g.test(Hf.userAgent),Ii=function(a,b){return function(c){c=c||x.event;var d=Sa(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=Ta(d,["a","area"]),e=!d||!d.href||Hi(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?Ja:Gi;if(c.defaultPrevented||!1===c.returnValue||c.da&&c.da()){if(d){var g={simulateDefault:!1},h=Ka(f,["wnc","nwnc"]);h&&La(a,d,g,f.wt,h)}}else{if(d){var g={},k,l=Ka(f,
["wnc","nwnc","nwc","wc"]);(k=La(a,d,g,f.wt,l))||(Ma(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&Pa;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=Qa(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},La=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||ja(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event=
"gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=Ji(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=Ki(b);g.eventTimeout=f;g.eventCallback=Li(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return ta(g)},
Ki=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},Oa=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},Qa=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(Hf.userAgent),e=Oa(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=x.frames&&x.frames[f]||x[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+G().getTime(),b.targetWindow=x.open("",b.targetWindowName));break;default:d&&!x.frames[e]?(b.simulateDefault=!1,c=!0):(x.frames[e]||(b.targetWindowName=e),b.targetWindow=x.frames[e]||x.open("",e))}return c},Ji=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||G().getTime(),500>G().getTime()-c&&x.setTimeout(Ji(a,b,c),25)))}},Li=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);N.gtmSubmitFormNow=!0;Na(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||G().getTime(),500>G().getTime()-c&&x.setTimeout(Li(a,b,c),25)}},Ka=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},Mi=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},Ma=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<Ni.length;c++)if(a.passingRules[c]){var d=Oi[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=Ni[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},ra=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(N.gtmHasClickListenerTag)return;N.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=Sa(a);b&&La("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Fi&&(Fi=pa(N.location));Mi(Gi,b||!1,c||!1,d,e);if(N.gtmHasLinkClickListenerTag)return;
N.gtmHasLinkClickListenerTag=!0;f="click";g=Ii(a,b||!1);break;case "FORM_SUBMIT":Mi(Ja,b||!1,c||!1,d,e);if(N.gtmHasFormSubmitListenerTag)return;N.gtmHasFormSubmitListenerTag=!0;f="submit";g=Ii(a,b||!1);break;default:return}T(N,f,g,h)},Hi=function(a){if(!Fi)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=oa(a);return Fi==pa(c)},Na=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
N.gtmFormElementSubmitter||(N.gtmFormElementSubmitter=N.createElement("form"));return N.gtmFormElementSubmitter.submit.call?N.gtmFormElementSubmitter.submit:a.submit},Pi=function(){var a=function(a){var b=S("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Gi=a("linkClickMap");Ja=a("formSubmitMap")};var Ca=function(a,b){var c=b||lb,d=c.onerror,e=!1;Ah&&!Ih("535.3")&&(e=!e);c.onerror=function(b,c,h,k,l){d&&d(b,c,h,k,l);a({message:b,fileName:c,ab:h,rc:k,error:l});return e}};var jj=function(a){if(!a)return!1;if(a[Db]&&Ua(a[U])){for(var b=a[U],c=0;c<b.length;c++)if(a[U]=b[c],wf(a))return!0;return!1}return wf(a)};var Ej=18,Fj=[],Gj=[],Hj=[],Ij=new vf,Jj=[],Z=[],Ni=[],Oi=[],Kj=function(){this.O=[]};Kj.prototype.set=function(a,b){this.O.push([a,b]);return this};Kj.prototype.resolve=function(a,b){for(var c={},d=0;d<this.O.length;d++){var e=Lj(this.O[d][0],a,b),f=Lj(this.O[d][1],a,b);c[e]=f}return c};var Mj=function(a){this.index=a};Mj.prototype.resolve=function(a,b){var c=Hj[this.index];if(c&&!b(c)){var d=c[Ha];if(a){if(a.get(d))return;a.set(d,!0)}c=Lj(c,a,b);a&&a.set(d,!1);return wf(c)}};
var _M=function(a){return new Mj(a)},Nj=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Lj(Fj[a[f]],b,c);g===Wa&&(e=!0);d.push(g)}return e?new eb(d):d.join("")}},_T=function(a){return new Nj(arguments)},Oj=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Lj(a[0],c,d);if(a[0]instanceof Mj&&b(8)&&b(16)){if(e===Wa)return e;var f=wa();Ij.set(f,e);return'google_tag_manager["GTM-M63JRHD"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new Oj(arguments)},Pj=function(a,b){this.A=a;this.wa=b},_R=function(a,b){return new Pj(a,b)};
var Lj=function(a,b,c){var d=a;if(a instanceof Mj||a instanceof Kj||a instanceof Nj||a instanceof Oj)return a.resolve(b,c);if(!(a instanceof Pj))if(Ua(a))for(var d=[],e=0;e<a.length;e++)d[e]=Lj(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=Lj(a[f],b,c))}return d},Sj=function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','6614976_2147479553',_html,true,'\n\x3cscript type\x3d\x22text/gtmscript\x22\x3e!function(b,e,f,g,a,c,d){b.fbq||(a\x3db.fbq\x3dfunction(){a.callMethod?a.callMethod.apply(a,arguments):a.queue.push(arguments)},b._fbq||(b._fbq\x3da),a.push\x3da,a.loaded\x3d!0,a.version\x3d\x222.0\x22,a.queue\x3d[],c\x3de.createElement(f),c.async\x3d!0,c.src\x3dg,d\x3de.getElementsByTagName(f)[0],d.parentNode.insertBefore(c,d))}(window,document,\x22script\x22,\x22https://connect.facebook.net/en_US/fbevents.js\x22);fbq(\x22init\x22,\x22286618111707433\x22);fbq(\x22track\x22,\x22PageView\x22);\x3c/script\x3e\n\x3cnoscript\x3e\x3cimg height\x3d\x221\x22 width\x3d\x221\x22 style\x3d\x22display:none\x22 src\x3d\x22https://www.facebook.com/tr?id\x3d286618111707433\x26amp;ev\x3dPageView\x26amp;noscript\x3d1\x22\x3e\x3c/noscript\x3e\n\n\n',1,_u,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=
Rj(c,a);return b},Rj=function(a,b){var c=b[a],d=c;if(c instanceof Mj||c instanceof Oj||c instanceof Nj||c instanceof Pj)d=c;else if(Ua(c))for(var d=[],e=0;e<c.length;e++)d[e]=Rj(c[e],b);else if("object"==typeof c){var d=new Kj,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],Rj(c[f],b))}return d},Uj=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
Fj[e[1]]);if(1==a)for(var f=Tj(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Gj[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=Tj(e[g]);3==a&&(c[d]=Fj[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Fj[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},Tj=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Ej;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);
2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Vj=function(a,b,c){a.push.apply(a,Uj(b,c))};var Wj;
var kg=function(){},ck=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var c={},d;for(d in a)if(a.hasOwnProperty(d)){var e=ak[d];e&&0==e.indexOf("vtp_")&&(c[e]=a[d])}c.__metadata=b;return c}return a},
gk=function(a){},ng=function(){},hk=function(a){},ik=function(a,b){},jk=function(a,b){},lg=function(a){};var kk,lk;
var xk=function(a){return function(){}},yk=function(a){return function(){}};var zk=function(a){var b=this;this.g=a;this.Z=this.gb=!1;this.va=[];this.qa=[];this.W=function(){if(b.i&&b.i.event){var c=b.i.event,d=b.g;}b.Z||Bf(b.va);Ef(b,1);if(sb[a])for(var e=0;e<sb[a].length;e++)sb[a].shift().W()};this.V=function(){if(b.i&&b.i.event){var c=b.i.event,d=b.g;}b.Z||Bf(b.qa);
Ef(b,2);if(sb[a])for(var e=0;e<sb[a].length;e++)sb[a].shift().V()};this.C=gb},Ak=function(a,b){a.va.push(b)},Bk=function(a,b){a.qa.push(b)},Ck=function(a){this.K=[];this.La=[];this.Xa={};this.bb=[];this.U=0;this.Ja={};this.Na={};this.Ma={};this.event=a};Ck.prototype.addListener=function(a){this.bb.push(a)};
var Dk=function(a){0<a.U||Bf(a.bb)},Ek=function(a,b,c,d,e,f){if(!c.Z){a.K[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=Ua(d)?d.slice():["or",d];e=Ua(e)?e.slice():[e];f=Ua(f)?f.slice():[f];a.Xa[b]=d;a.Ja[b]=0<e.length;a.Na[b]=0<f.length;a.U++;var g=function(){0<a.U&&!a.Ja[b]&&!a.Na[b]&&a.U--;Dk(a)};Ak(c,g);Bk(c,g)}},Jk=function(a){for(var b=[],c={},d=0;d<a.K.length;c={P:c.P},d++)if(c.P=a.K[d],c.P){var e=a.Xa[d],f=a.Ja[d],g=a.Na[d];if(0!=e.length||f||g){if(0<e.length)for(var h=Fk(e,
c.P.C),k=0;k<e.length;k++)e[k]instanceof Pj&&e[k].A!=d&&Gk(a,e[k].A,h);(f||g)&&Hk(a,d,function(a){return function(){0<a.P.i.U&&a.P.i.U--;Dk(a.P.i)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.K[b[d]].C();for(d=0;d<a.La.length;d++){var l=a.La[d];Ik(l);0<l.length&&l[0].C()}},Gk=function(a,b,c){a.K[b]&&(Ak(a.K[b],function(){c(b,!0)}),Bk(a.K[b],function(){c(b,!1)}))},Fk=function(a,b){var c=gb,d=!1;return function(e,f){var g;a:{for(var h=0;h<a.length;h++)if(a[h]instanceof Pj&&a[h].A===e||a[h]===e){g=
h;break a}g=-1}d||0>g||("or"==a[0]?f?(d=!0,b()):(a.splice(g,1),1==a.length&&(d=!0,c())):f?(a.splice(g,1),1==a.length&&(d=!0,b())):(d=!0,c()))}},Hk=function(a,b,c){var d=[],e=!1,f=function(b){var c,g,h=Z[b];if(a.event.f(h)){}else g=Kk(h,b,a.event.f,a);if(c=g){var k=Lk(b,!0);0<k.length&&f(k[0].A);d.push(c);var l=Lk(b,!1);0<l.length&&f(l[0].A)}else e=
!0};f(b);if(!e){for(var g=0;g<d.length;g++){var h=d[g],k=Lk(h.g,!0);if(0<k.length){var l=d[g-1],m=Mk(h);Ak(l,m);0==k[0].wa?Bk(l,m):Bk(l,c)}var n=Lk(h.g,!1);0<n.length&&(m=Mk(d[g+1]),Ak(h,m),0==n[0].wa?Bk(h,m):Bk(h,c))}Ak(d[d.length-1],c);Bk(d[d.length-1],c);a.La.push(d)}},Lk=function(a,b){var c=b?te:Ke,d=Z[a],e=void 0===d[c]?[]:d[c];return Ua(e)?e:[e]},Mk=function(a){return function(){a.C()}},Ik=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.g,f=rb[e],g=f.firingOption;0!=g&&(1==g&&void 0!==
d.i.Ma[e]||2==g&&void 0!==f.state)&&b.push(d)}var h=Nk(b),k;for(k in h)if(h.hasOwnProperty(k)){for(var l=void 0,m=void 0,n=h[k],q=n[0],u=n[n.length-1],y,r=0;r<a.length;r++){var z=a[r];!l&&z.g==q&&0<r&&(l=a[r-1]);z.g==u&&r<a.length-1&&(m=a[r+1]);if(-1<tf(n,z.g))if(y=a.splice(r,1)[0],z.g==u)break;else r--}if(y){var B=Number(k),A=l,C=m;if(A){var I=A.va[0],K=A.qa[0],E=A;E.va=[];E.qa=[];Ak(A,I);Bk(A,K)}if(A&&C){var D=Mk(C);Ak(A,D);var J=Lk(A.g,!1);0<J.length&&J[0].A!=B&&0==J[0].wa&&Bk(A,D);var H=Lk(C.g,
!0);0<H.length&&H[0].A!=B&&0==H[0].wa&&Bk(A,D)}}}},Nk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Lk(a,!0);0<b.length&&f(b[0].A);e.push(a);var c=Lk(a,!1);0<c.length&&f(c[0].A)};f(d.g);b[d.g]=e}Ok(a,b);return b},Ok=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<tf(b[e],d)){delete b[d];break}}};var Qk=function(a,b,c){return function(){a[fd]=b.W;a[gd]=b.V;var d=b.g,e=b.i&&b.i.Ma[d],f=rb[d]&&rb[d].state,g=e?void 0!==e:b.gb||b.Z,h=rb[d]&&rb[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){Ef(b,0);var m=b.i?b.i.event:void 0;a=Pk(a,c);if(m){var n=a;ik(m,d)}wf(a,b.W,b.V)}else k&&0==f||l&&0==e?sb[d].push(b):k&&1==f||l&&1==e?b.W():b.V()}},Pk=function(a,b){a=Lj(a,new vf,b);return a},Kk=function(a,b,c,d){var e=d&&d.K,f;if(f=e)a:{if(e&&Ua(e)&&0!=e.length)for(var g=0;g<e.length;g++)if(e[g]&&e[g].g===b){f=e[g];break a}f=void 0}var h=f||new zk(b);h.i=d;Ak(h,xk(a));Bk(h,yk(a));h.C=Qk(a,h,c);return h};var Vk=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Jj[b]&&Lj(Jj[b],new vf,c),e=d;d&&(e=jj(d));a[b]=[e,d]}return a[b]}},fk=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.T(c[d],a.f)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.T(e[d],a.f)[0])return!1;return!0},Wk=function(a){for(var b=new Ck(a),c=0;c<Ej;c++)if(a.la[c]&&!a.ua[c])if(a.f(Z[c])){}else{var d=a.X[c],e=Kk(d,c,a.f,b);Ek(b,c,e,d[Dc],d[te],d[Ke]);if(d[tb])break}b.addListener(a.ma);Jk(b);Dk(b)},Xk=!1,eg=function(a,b,c,d,e){switch(b){case "gtm.js":if(Xk)return!1;Xk=!0;break;case "gtm.sync":if(V("gtm.snippet")!=pb)return!1}for(var f={id:a,name:b,ma:d||gb,la:Tj(),ua:Tj(),T:Vk(),f:vg(c)},g=[],h=0;h<Ni.length;h++)if(fk(f,Ni[h])){g[h]=!0;for(var k=
f,l=Ni[h],m=l[1],n=0;n<m.length;n++)k.la[m[n]]=!0;for(var q=l[3],n=0;n<q.length;n++)k.ua[q[n]]=!0}else g[h]=!1;ik(f);var y=[];for(var r=0;r<Ej;r++)if(f.la[r]&&!f.ua[r])if(f.f(Z[r])){}else{y[r]=Z[r];}f.X=y;Wk(f);e&&P(e)&&e({passingRules:g,resolvedTags:f.X});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var K in f.X)if(f.X.hasOwnProperty(K)){var E=f.X[K],D;if(!(D=void 0==E[Ha])){var J=E[Ha];D=!("function"!=typeof String.prototype.startsWith?0===J.indexOf("_implicit"):J.startsWith("_implicit"))}if(D)return!0}return!1};var Zk=function(){};var $k=function(){};var Yk={macro:function(a){if(Ij.contains(a))return Ij.get(a)}};Yk.dataLayer=Tf;Yk.onHtmlSuccess=ih(!0);Yk.onHtmlFailure=ih(!1);Yk.callback=function(a){Ea.hasOwnProperty(a)&&P(Ea[a])&&Ea[a]();delete Ea[a]};
Yk.vb=function(){var a=x.google_tag_manager;a||(a=x.google_tag_manager={});Xa=a;if(a["GTM-M63JRHD"]){var b=Xa.zones;b&&b.registerNatural("GTM-M63JRHD")}else{a["GTM-M63JRHD"]=Yk;Pi();Fj.push.apply(Fj,Sj());Vj(Gj,0,"3:0,3:1,5:2,0:3,1:4,3:6,6:7,4:8,7:9,3:10,5:11,5:12,2:13,5:14,2:15,3:16,5:17,5:18");Vj(Hj,1,"G,AY,AoB,AIG,AAY,CAg");Vj(Jj,1,"Z");Vj(Z,1,"gH");Vj(Ni,2,"B:B::");Vj(Oi,4,"5:");for(var c=0;c<Z.length;c++){var d=Z[c],
e=1;d[Rd]?e=2:d[bf]&&(e=0);rb[c]={firingOption:e,state:void 0};sb[c]=[]}ag();qg();var n=x;if("interactive"==N.readyState&&!N.createEventObject||"complete"==N.readyState)Jf();else{T(N,"DOMContentLoaded",Jf);T(N,"readystatechange",Jf);if(N.createEventObject&&N.documentElement.doScroll){var q=!0;try{q=!n.frameElement}catch(u){}q&&
Lf()}T(n,"load",Jf)}"complete"===N.readyState?Of():T(x,"load",Of);$k();Zk()}};Yk.vb();var _vs="res_ts:1490697636120000,srv_cl:153841216,ds:live,cv:1";
})()
